name: Build Windows 32-bit Binary
permissions:
  contents: write
on:
  push:
    branches:
      - main
      - master
    tags:
      - v[0-9]+.*
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-windows-32bit:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: i686-pc-windows-msvc
          components: clippy, rustfmt
      - name: Verify target installation
        run: rustup target list --installed
      - name: Build Example
        run: cd examples && cargo build --release --target i686-pc-windows-msvc
        timeout-minutes: 30
      - name: Package Example
        shell: bash
        env:
          NAME: unifiedlog_iterator
          TARGET: i686-pc-windows-msvc
        run: .github/scripts/package.sh
      - name: Upload Artifacts (Always)
        uses: actions/upload-artifact@v4
        with:
          name: windows-32bit-binary
          path: "unifiedlog_iterator*"
          retention-days: 90
      - name: Release (Tags Only)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: "unifiedlog_iterator*"
          name: "${{ github.ref_name }} - Windows 32-bit Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
